name: Publish Demo to github pages
on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - run: npm ci
            - run: npm run build-demo
            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v1
              with:
                  target_branch: gh-pages
                  build_dir: build
              env:
                  PALAVYR_TEST_API_KEY: ${{ secrets.PALAVYR_TEST_API_KEY }}
